### ISSUE TITLE
Come up with a better name for slacs

### ISSUE THREAD

**Issue by shymega** [xtensis-editor/xtensis-core#6]
'slacs' sounds _awfully_ like 'slack'

It's confusing, and quite a few people have spelled it wrong.

Thoughts?

**Comment by silversquirl** [comment]
Ironic that you spelled 'spelled' wrong ;)

**Comment by shymega** [comment]
>:( Any ideas though? :P

**Comment by silversquirl** [comment]
Well, given that it's a rust-based editor, what about `rudit` or `rus`?

**Comment by shymega** [comment]
I'm pretty settled on `xtensis` at the moment.
In the next few days, I'll begin migrating this org --> new org.
Also gonna be relicensing back to GPLv3, hopefully last move.
(Need to check the legal standing first)

Xtensis is pronounced as 'exten-sys'.
